In [1]:
import numpy as np

In [2]:
x=np.array([1,2,3])

<br> Propriétés d'un obj math 

In [3]:
x.ndim

1

In [4]:
x.shape

(3,)

In [5]:
x.dtype

dtype('int32')

In [8]:
x=np.array([1,2,3],dtype=np.uint8)

<br>Opératures sur vecteurs


In [10]:
x=np.array([1,2,3])
y=np.array([1,1,1])
z=x+y

In [12]:
y=np.ones(shape=(3),dtype=np.int16)

In [13]:
y

array([1, 1, 1], dtype=int16)

In [14]:
x-y

array([0, 1, 2])

In [15]:
x*y #element wise multiplication

array([1, 2, 3])

In [16]:
z=[]
for i in range(len(x)):
    p=x[i]*y[i]
    z.append(p)
z=np.array(z)
z

array([1, 2, 3])

In [17]:
x**y

array([1, 2, 3], dtype=int32)

In [ ]:
z=np.empty(shape=x.shape,dtype=x.dtype)
for i in range(len(x)):

<br> Fonctions sur les vecteurs

In [18]:
ages=np.array([28,35,54,24])

In [19]:
ages.min()

24

In [21]:
ages.argmin()

3

In [22]:
ages.argmax()

2

In [23]:
ages.sort()

In [24]:
ages

array([24, 28, 35, 54])

In [25]:
np.mean(ages)

35.25

In [26]:
np.sort(ages)

array([24, 28, 35, 54])

In [27]:
np.sort(ages)[::-1]

array([54, 35, 28, 24])

In [28]:
np.var(ages)

132.6875

In [31]:
ages1=np.array([29,30,29,31,30,31])

In [32]:
np.mean(ages1)

30.0

In [33]:
ages2=np.array([20,30,40,50,30,10])

In [34]:
np.mean(ages2)

30.0

In [35]:
np.var(ages1)

0.6666666666666666

In [36]:
np.var(ages2)

166.66666666666666

<br> Operations sur matrices

In [37]:
X=np.array([[1,2,3],[4,5,6]])
Y=np.array([[1,1,1],[1,1,1]])
Z=X+Y
Z

array([[2, 3, 4],
       [5, 6, 7]])

In [38]:
X-Z

array([[-1, -1, -1],
       [-1, -1, -1]])

In [39]:
X*Y

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
X**Y

array([[1, 2, 3],
       [4, 5, 6]])

<br>Fonctions sur matrices

In [41]:
x=np.array([1,2,3])
y=np.array([5,6,7])
np.dot(x,y) #produit scalaire

38

In [47]:
X=np.array([[1,2,3],[4,5,6]])
Y=np.array([[2],[3],[4]])
np.dot(X,Y)

array([[20],
       [47]])

In [48]:
X

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
X.min(axis=0)

array([1, 2, 3])

In [51]:
X.min(axis=1) #1 pour les lignes f kol linges yaati min

array([1, 4])

In [55]:
X.sum()

21

In [56]:
X.sum(axis=0)

array([5, 7, 9])

In [58]:
X.mean(axis=0)

array([2.5, 3.5, 4.5])

<br> Operations entre vecteurs et scalaires

In [59]:
x=np.array([1,2,3])

In [60]:
2*x

array([2, 4, 6])

In [61]:
2+x

array([3, 4, 5])

In [62]:
x/2

array([0.5, 1. , 1.5])

<br> Operationes entre matrices et vecteurs

In [68]:
X=np.array([[[1,2],[2,3],[3,4]]])
X

array([[[1, 2],
        [2, 3],
        [3, 4]]])

In [69]:
x=np.array([2,2])
x

array([2, 2])

In [70]:
X+x

array([[[3, 4],
        [4, 5],
        [5, 6]]])

In [71]:
X/x

array([[[0.5, 1. ],
        [1. , 1.5],
        [1.5, 2. ]]])

<b>Exercice </b>
soit un emp 'Ali' ayant comme age 28 et salaire 2100.75
soit l ensemble d 'employés:
<br>-'Salma' (age=40,2200.76)
<br>-'Rahma' (age=28,3200.76)
<br>-'Ahmed' (age=45,2100.76)


In [97]:
mat1=np.array([[40,2200.76],[28,3200.76],[45,2100.76]])
mat1
noms=['Salma','Rahma','Ahmed']

In [75]:
mat2=np.array([28,2100.75])

In [82]:
#age 1er emp
mat1[0,0]

40.0

In [83]:
#premier emp
mat1[0,:]

array([  40.  , 2200.76])

In [84]:
#dernier emp
mat1[-1,:]

array([  45.  , 2100.76])

In [85]:
#matrice contennat premier et dernie employe
mat1[[1,-1],:]

array([[  28.  , 3200.76],
       [  45.  , 2100.76]])

In [86]:
#emp dans l age < 40
mat1[:,0]<40

array([False,  True, False])

In [90]:
dist=np.empty(shape=(mat1.shape[0]))
for i in range(mat1.shape[0]) :
    d=mat2-mat1[i,:]
    d2=d**2
    s=np.sum(d2)
    distance=np.sqrt(s)
    dist[i]=distance
    

    

In [91]:
dist

array([ 100.72735527, 1100.01      ,   17.00000294])

In [93]:
indice_emp_proche=np.argmin(dist)
indice_emp_proche


2

In [98]:
noms[indice_emp_proche]

'Ahmed'